---
channel: stable
addons:
  otelcol:
    repository: mcinnes01/ha-addon-otelcol
    target: otelcol
    image: ghcr.io/mcinnes01/{arch}-ha-addon-otelcol
  loki:
    repository: mcinnes01/ha-addon-grafana-loki
    target: loki
    image: ghcr.io/mcinnes01/{arch}-addon-grafana-loki
  mimir:
    repository: mcinnes01/ha-addon-grafana-mimir
    target: mimir
    image: ghcr.io/mcinnes01/{arch}-addon-grafana-mimir
  tempo:
    repository: mcinnes01/ha-addon-grafana-tempo
    target: tempo
    image: ghcr.io/mcinnes01/{arch}-addon-grafana-tempo
